#!/usr/bin/env python3
"""Build compact assistant pack retrieval databases.

KDB.TXT is the runtime recall surface. HELP.TXT and KNOW.TXT stay readable
authoring files; this script compiles their rows into shorter keyword-indexed
records so the DOS shell scans less text before answering.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

from assistant_pack_contract import HelpRow, PackContract, load_all_pack_contracts


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PACK_ROOT = ROOT / "assets" / "gpt2_basic" / "PACKS"

STOPWORDS = {
    "the",
    "and",
    "for",
    "with",
    "what",
    "when",
    "where",
    "why",
    "how",
    "can",
    "you",
    "your",
    "this",
    "that",
    "from",
    "about",
    "into",
    "should",
    "would",
    "could",
    "then",
    "than",
    "they",
    "them",
    "that",
    "there",
    "here",
    "will",
    "each",
    "use",
    "uses",
}


@dataclass(frozen=True)
class KdbRow:
    terms: str
    title: str
    body: str


def words(text: str) -> list[str]:
    return re.findall(r"[a-z0-9][a-z0-9.:-]*", text.lower())


def compact_terms(row: HelpRow, limit: int = 18) -> str:
    selected: list[str] = []
    seen: set[str] = set()
    for source in (row.key, row.title, row.text):
        for word in words(source):
            cleaned = word.strip(".:-")
            if len(cleaned) < 3 or cleaned in STOPWORDS:
                continue
            if cleaned not in seen:
                selected.append(cleaned)
                seen.add(cleaned)
            if len(selected) >= limit:
                return " ".join(selected)
    return " ".join(selected)


def kdb_rows(pack: PackContract) -> list[KdbRow]:
    rows: list[KdbRow] = []
    seen: set[tuple[str, str]] = set()
    for row in (*pack.help_rows, *pack.knowledge_rows):
        identity = (row.title, row.text)
        if identity in seen:
            continue
        seen.add(identity)
        terms = compact_terms(row)
        if not terms:
            terms = row.key
        rows.append(KdbRow(terms, row.title, row.text))
    return rows


def render_kdb(pack: PackContract) -> str:
    lines = [
        "# terms|title|body",
        "# Generated by scripts/build_assistant_kdb.py from HELP.TXT and KNOW.TXT.",
    ]
    for row in kdb_rows(pack):
        lines.append(f"{row.terms}|{row.title}|{row.body}")
    return "\n".join(lines) + "\n"


def write_or_check(pack_root: Path, write: bool) -> int:
    failures: list[str] = []
    for pack in load_all_pack_contracts(pack_root):
        expected = render_kdb(pack)
        target = pack.kdb_path
        if write:
            target.write_text(expected, encoding="ascii")
            print(f"WROTE_ASSISTANT_KDB|pack={pack.pack_id}|path={target}|rows={len(kdb_rows(pack))}")
            continue
        current = target.read_text(encoding="ascii") if target.exists() else ""
        if current != expected:
            failures.append(pack.pack_id)
            print(f"ASSISTANT_KDB_STALE|pack={pack.pack_id}|path={target}")
        else:
            print(f"ASSISTANT_KDB_OK|pack={pack.pack_id}|rows={len(kdb_rows(pack))}")
    if failures:
        print("ASSISTANT_KDB_CHECK_FAILED|packs=" + ",".join(failures))
        return 1
    print("PROBE_OK assistant_kdb=1")
    return 0


def self_test() -> None:
    row = HelpRow("fat image full", "FAT image full", "Remove host-only training files or grow the disk image.")
    terms = compact_terms(row)
    assert "fat" in terms
    assert "image" in terms
    assert "training" in terms
    rendered = render_kdb(load_all_pack_contracts(DEFAULT_PACK_ROOT)[0])
    assert rendered.startswith("# terms|title|body\n")
    assert "Better prompts" in rendered
    print("PROBE_OK assistant_kdb_self_test=1")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pack-root", type=Path, default=DEFAULT_PACK_ROOT)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return
    raise SystemExit(write_or_check(args.pack_root, write=args.write or not args.check))


if __name__ == "__main__":
    main()
