#!/usr/bin/env python3
"""Build a small hand-curated gold corpus for GPT2-BASIC.

This corpus is intentionally narrow. It teaches the DOS model the exact kinds
of explanations it needs to produce, without mining reports, README prose, code
paths, scoring instructions, or previous malformed generations.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

from gpt2_basic_tokenizer import BYTE_OFFSET, BYTE_VOCAB_SIZE, build_lexicon_tokenizer


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VERSION = "v4"
DEFAULT_OUTPUTS = {
    "v1": ROOT / "data" / "domain_curriculum" / "gold_curriculum_v1.txt",
    "v2": ROOT / "data" / "domain_curriculum" / "gold_curriculum_v2.txt",
    "v3": ROOT / "data" / "domain_curriculum" / "gold_curriculum_v3.txt",
    "v4": ROOT / "data" / "domain_curriculum" / "gold_curriculum_v4.txt",
}
DEFAULT_REPORTS = {
    "v1": ROOT / "qemu" / "evidence" / "gold_curriculum_v1_report.md",
    "v2": ROOT / "qemu" / "evidence" / "gold_curriculum_v2_report.md",
    "v3": ROOT / "qemu" / "evidence" / "gold_curriculum_v3_report.md",
    "v4": ROOT / "qemu" / "evidence" / "gold_curriculum_v4_report.md",
}


BANNED_PATTERNS = [
    r"\banswer should\b",
    r"\bshould mention\b",
    r"\bcontinue with\b",
    r"\btie them to\b",
    r"\btarget behavior\b",
    r"\brelevant words\b",
    r"\bif (?:a )?user asks\b",
    r"\bwhen the prompt\b",
    r"\bcorrect answer\b",
    r"\buseful continuation\b",
    r"\bthe key point is\b",
    r"\bpractical rule\b",
    r"\bdrifting into generic prose\b",
    r"\bimplementation should\b",
    r"\bGPT2[A-Z0-9]*\.(?:TXT|BIN|EXE)\b",
    r"\b(?:assets|scripts|src|data|qemu|evidence|MODEL)[/\\][^\s]+",
    r"\b[\w./\\-]+\.(?:md|py|bas|json|log|txt|bin|exe)\b",
    r"\|",
    r"`",
]


CORRUPT_PATTERNS = [
    r"\b\w*(?:saloing|satizimblang|cheful|plort|atthion|singht|andul|reun)\w*\b",
    r"\b\w*(?:gratenerner|sformpating|tontext|truntime|prameter|seped|benverations)\w*\b",
    r"\b[a-z]*([a-z])\1\1[a-z]*\b",
]


@dataclass(frozen=True)
class Topic:
    key: str
    questions: tuple[str, ...]
    facts: tuple[str, ...]
    detail: tuple[str, ...]
    contrast: tuple[str, ...]


TOPICS: tuple[Topic, ...] = (
    Topic(
        "real inference",
        (
            "What makes this real inference?",
            "Is this DOS demo using a trained model?",
            "Why is the generated text not a script?",
        ),
        (
            "The continuation comes from trained weights, transformer layers, logits, and a sampler running inside the DOS program.",
            "The program encodes the prompt, runs attention and feed-forward layers, and chooses the next token from model logits.",
            "A scripted text table would not prove anything about the runtime; this path uses the exported checkpoint during generation.",
        ),
        (
            "Real inference is visible when changing the prompt changes the hidden state and the next-token distribution.",
            "The host is used for training and export, while the DOS machine performs the forward pass.",
            "The fixed-point run is trusted only after phase vectors match the host reference closely enough.",
        ),
        (
            "This is not a canned completion.",
            "The result is not copied from a prompt table.",
            "The demo is honest because the generated bytes come from model state.",
        ),
    ),
    Topic(
        "486 target",
        (
            "GPT2 BASIC on a 486",
            "What is realistic for a language model on a 486?",
            "Why keep the model small for old PCs?",
        ),
        (
            "A 486-era machine can run a tiny transformer when the model keeps memory, context length, and arithmetic cost under control.",
            "The useful target is a compact checkpoint that produces short technical continuations at a measurable speed.",
            "The runtime needs predictable arrays, fixed-size buffers, and no dependence on a modern service during generation.",
        ),
        (
            "A 486SX has no required floating point unit, so fixed-point arithmetic is part of the production path.",
            "A larger model can improve text only if it still fits memory and keeps tokens per second usable.",
            "The vocabulary helps by replacing common technical words and phrases with single tokens.",
        ),
        (
            "The goal is not a modern assistant.",
            "The goal is a credible old-PC language model.",
            "The constraint makes the system easier to audit.",
        ),
    ),
    Topic(
        "DOS timing",
        (
            "How should a DOS model report timing?",
            "What belongs in a timing result?",
            "How can timing claims stay honest?",
        ),
        (
            "A timing result needs generated tokens, elapsed seconds, tokens per second, the model profile, and the measurement basis.",
            "The timed section belongs inside the decode loop so loading files and boot time do not distort generation speed.",
            "Emulator timing is useful for iteration, but physical hardware timing is the stronger evidence when a board is available.",
        ),
        (
            "The report needs enough context for another run to repeat the measurement.",
            "Prompt length and output length matter because attention work grows with the active context.",
            "Speed numbers are useful only beside the model shape and memory footprint.",
        ),
        (
            "Host stopwatch numbers alone are not hardware evidence.",
            "A bare speed claim is incomplete without the model profile.",
            "A timing result is a measurement, not a slogan.",
        ),
    ),
    Topic(
        "cache reuse",
        (
            "Explain why a cache matters for text generation",
            "Why reuse key and value vectors?",
            "How does a cache help the decode loop?",
        ),
        (
            "A cache matters because the model can reuse key and value vectors from earlier tokens instead of rebuilding the full attention history.",
            "Cache reuse saves repeated attention work while preserving enough context for coherent text.",
            "On an old PC, the cache trades fixed memory for fewer operations in each next-token step.",
        ),
        (
            "The cache must be sized predictably because DOS memory is limited.",
            "A small context keeps cache memory manageable and keeps attention work bounded.",
            "A cache changes runtime cost, not the trained weights.",
        ),
        (
            "Without a cache, each generated token repeats more work.",
            "A cache is useful only when its memory cost fits the target machine.",
            "The cache is an engineering tradeoff, not a quality shortcut.",
        ),
    ),
    Topic(
        "fixed point",
        (
            "Describe fixed point inference in one sentence",
            "Why use fixed-point arithmetic?",
            "How does the DOS runtime avoid depending on an FPU?",
        ),
        (
            "Fixed-point inference stores weights as scaled integers and computes logits with predictable integer arithmetic.",
            "A no-FPU machine can run the transformer when multiplies, clamps, and lookup tables replace floating point operations.",
            "Phase-vector checks compare the DOS fixed-point path with the host reference before the checkpoint is trusted.",
        ),
        (
            "The scale must be chosen carefully so values keep useful precision without overflowing.",
            "Attention, feed-forward layers, normalization, and output logits all need checked integer behavior.",
            "The exponential table keeps softmax practical on hardware without fast floating point.",
        ),
        (
            "Fixed point is not just compression.",
            "Integer arithmetic still has to match the model closely enough.",
            "Every scale and clamp is part of the correctness contract.",
        ),
    ),
    Topic(
        "old PC limits",
        (
            "What limits a tiny transformer on old PCs?",
            "Why can old hardware only run a small model?",
            "Where does a DOS transformer spend its budget?",
        ),
        (
            "A tiny transformer on old PCs is limited by weight bytes, context length, cache memory, integer arithmetic, and the output vocabulary.",
            "The output head grows with vocabulary size, so every extra token adds weights and logits work.",
            "The context window is a budget: more history improves continuity, but attention and cache memory get more expensive.",
        ),
        (
            "Memory pressure comes from weights, activations, logits, token arrays, and work buffers.",
            "Speed pressure comes from matrix-vector products, attention scores, activation functions, and sampling.",
            "A useful checkpoint balances quality with predictable memory and measured tokens per second.",
        ),
        (
            "Capacity alone does not make the old-PC model better.",
            "A larger checkpoint can be slower without producing cleaner text.",
            "The practical limit is the whole runtime, not just file size.",
        ),
    ),
    Topic(
        "profile comparison",
        (
            "Why compare model profiles before choosing one?",
            "How should profiles be selected?",
            "What makes one checkpoint a better default?",
        ),
        (
            "Profiles need comparison by held-out quality, tokens per second, memory use, parameter count, context length, and vector parity.",
            "The best default is the smallest profile that produces clean text while passing runtime evidence.",
            "A larger profile earns its cost only when measured quality improves enough to justify slower generation and higher memory use.",
        ),
        (
            "A profile table is useful when it puts quality and speed beside memory.",
            "The default model needs both host quality evidence and DOS runtime evidence.",
            "The model shape explains the cost: layers, embedding size, heads, context length, and vocabulary all matter.",
        ),
        (
            "The largest checkpoint is not automatically the best checkpoint.",
            "A profile without timing evidence is not ready.",
            "Quality, speed, and memory have to be read together.",
        ),
    ),
    Topic(
        "BASIC runtime",
        (
            "How does the BASIC transformer runtime work?",
            "What does the DOS program do during generation?",
            "Why use plain arrays in the runtime?",
        ),
        (
            "The BASIC runtime uses arrays for tokens, embeddings, cache vectors, logits, weights, and fixed-point work buffers.",
            "Generation loads the checkpoint, encodes the prompt, runs transformer layers, masks invalid output, and decodes printable text.",
            "Plain arrays make memory use visible and keep the implementation understandable on old development tools.",
        ),
        (
            "The runtime stops instead of pretending when required model files are missing.",
            "The output path uses the same tokenizer contract as the host tools.",
            "The DOS program is a real inference runner, not a training system.",
        ),
        (
            "The implementation favors explicit loops over hidden libraries.",
            "The runtime is small enough to inspect.",
            "A plain implementation makes failure modes easier to diagnose.",
        ),
    ),
    Topic(
        "vocabulary",
        (
            "Why does vocabulary content matter?",
            "How does a lexicon help this small model?",
            "What makes a vocabulary piece useful?",
        ),
        (
            "A lexicon helps when common technical words and short phrases become single tokens that the model can emit cleanly.",
            "Vocabulary content matters more than raw size because bad pieces preserve bad habits from the corpus.",
            "Useful pieces are complete words, common domain phrases, punctuation, and short endings that appear in clean prose.",
        ),
        (
            "The vocabulary must not learn scoring instructions, report paths, or broken generated text.",
            "A clean lexicon reduces spelling burden and lowers the chance of malformed byte-built words.",
            "The top pieces need to look like domain language, not training scaffolding.",
        ),
        (
            "A large vocabulary can make bad data worse.",
            "The tokenizer can only preserve what the corpus gives it.",
            "Clean content makes the lexicon useful.",
        ),
    ),
    Topic(
        "failure behavior",
        (
            "What happens if model files are missing?",
            "Why reject fake output paths?",
            "How should the demo fail?",
        ),
        (
            "If required model files are missing, the DOS program reports the problem and stops instead of printing fake generated text.",
            "A fake output path would hide the real engineering problem and make timing or quality evidence meaningless.",
            "The system is credible because it distinguishes diagnostics from production inference.",
        ),
        (
            "A clear failure is better than a convincing fake response.",
            "The user needs to know whether the checkpoint loaded and whether generation used trained weights.",
            "Evidence logs matter because they show the program executed the real path.",
        ),
        (
            "The demo must not pretend.",
            "A missing checkpoint is an error, not a chance to improvise.",
            "Trust comes from explicit runtime behavior.",
        ),
    ),
)


PAIRINGS = (
    (0, 4),
    (0, 7),
    (1, 5),
    (1, 8),
    (2, 6),
    (2, 4),
    (3, 5),
    (3, 7),
    (4, 5),
    (5, 6),
    (6, 8),
    (7, 9),
)


HELDOUT_REINFORCEMENT_DOCS = (
    "Explain why a cache matters for text generation. A cache keeps previous key and value vectors available, so each new token can attend to history without rebuilding every earlier vector. This saves speed while using a predictable block of memory.",
    "Explain why a cache matters for text generation. Cache reuse helps old hardware because the decode loop only adds the newest token work instead of repeating the full attention setup. The benefit must still fit inside the DOS memory budget.",
    "A cache matters for text generation because context is reused one token at a time. The model still attends to earlier tokens, but the runtime can store the key and value vectors that do not change. That makes speed and memory a deliberate tradeoff.",
    "Key and value caching is not a different model. It is a runtime technique that keeps earlier attention data ready for the next step. The output can stay coherent while the machine avoids repeated work.",
    "How should a DOS model report timing? It should print generated tokens, elapsed seconds, tokens per second, model profile, context length, and whether the run used emulator timing or physical hardware timing.",
    "How should a DOS model report timing? The measurement belongs around the decode loop, not around boot, file loading, or setup. A clear timing result names the checkpoint and says how many tokens were generated.",
    "A useful DOS timing report includes seconds, token count, tokens per second, memory use, and model shape. QEMU timing is helpful for development, while real hardware timing is the stronger claim.",
    "Timing claims stay honest when the report gives enough detail to repeat the run. The model profile, prompt length, output length, and measurement source all matter.",
    "What limits a tiny transformer on old PCs? The limits are weight bytes, cache memory, context length, integer arithmetic, output vocabulary, and the number of operations per generated token.",
    "What limits a tiny transformer on old PCs? Memory controls how large the checkpoint and cache can be, while speed controls how many matrix and attention operations are practical. A small model has to balance both.",
    "Old PCs limit a transformer through memory capacity, slow arithmetic, and a short usable context. The vocabulary can help by reducing token count, but the output head also gets larger as the vocabulary grows.",
    "The practical limit on old hardware is not just file size. A checkpoint also needs enough free memory for activations, logits, token history, cache vectors, and work buffers.",
    "Describe fixed point inference in one sentence. Fixed-point inference represents weights and activations as scaled integers so the DOS runtime can run transformer math without depending on floating point hardware.",
    "Describe fixed point inference in one sentence. It is transformer inference with integer-scaled weights, checked clamps, lookup tables, and logits that stay close to the host reference.",
    "Fixed-point inference works when every scale is chosen to preserve useful precision while avoiding overflow. Vector parity is the evidence that the integer path still matches the trained model closely enough.",
    "The DOS fixed-point path replaces floating point operations with integer multiplies, shifts, clamps, and lookup tables. That makes a no-FPU machine a realistic target.",
    "Why compare model profiles before choosing one? Profiles show the tradeoff between quality, speed, memory, parameter count, context length, and vocabulary size. The best default is the smallest profile that passes the evidence.",
    "Why compare model profiles before choosing one? A larger checkpoint is only better when measured quality improves enough to justify extra memory and slower generation. Quality and runtime evidence have to be considered together.",
    "A profile comparison should put held-out quality beside tokens per second and peak memory. That makes it clear whether a larger vocabulary or hidden size is helping the real target machine.",
    "The default profile should be selected from evidence, not from size alone. A compact model that produces clean text at a usable speed can be a better default than a larger model that drifts.",
)


RUNTIME_REINFORCEMENT_DOCS = (
    "What makes this real inference? The prompt is encoded into tokens, the transformer updates hidden state, the output head produces logits, and the sampler chooses the next token from the trained checkpoint.",
    "What makes this real inference? The DOS program loads model files and computes the continuation with fixed-point transformer layers. Changing the prompt changes the state and the next-token distribution.",
    "A real inference demo does not print a canned answer. It uses trained weights, attention layers, feed-forward layers, logits, and a tokenizer contract shared with the host tools.",
    "GPT2 BASIC on a 486 is useful when the model stays small enough for memory and arithmetic but still produces clear technical prose. The target is a credible old-PC transformer, not a modern assistant.",
    "GPT2 BASIC on a 486 needs fixed-point arithmetic, predictable buffers, short context, measured timing, and a vocabulary that reduces spelling burden without bloating the output head.",
    "A 486-compatible run is interesting because the machine must load the checkpoint and perform the forward pass locally. The host can train and export, but generation belongs to the DOS runtime.",
    "DOS language models need compact weights, clear failure behavior, reproducible timing, simple file formats, and a tokenizer that both host and runtime understand.",
    "DOS language models need enough vocabulary to say technical words cleanly, but not so much output head work that each token becomes too slow. The useful model balances both limits.",
    "A DOS language model also needs honest diagnostics. Missing files, bad vocabularies, and shape mismatches should stop with a clear message instead of printing fake text.",
    "A BASIC transformer runtime uses plain arrays for weights, tokens, cache vectors, hidden states, and logits. That makes memory behavior visible and keeps the implementation inspectable.",
    "A BASIC transformer runtime loads the checkpoint, encodes the prompt, runs attention and feed-forward layers, masks invalid output, and decodes printable text.",
    "Plain BASIC loops are slower than modern libraries, but they make the old-PC path understandable. The code is useful because the constraints can be inspected.",
    "To improve performance on real hardware, reduce repeated work, keep memory access predictable, choose a compact profile, and measure tokens per second inside the decode loop.",
    "To improve performance on real hardware, the runtime should favor fixed-size arrays, cached attention data, simple sampling rules, and a vocabulary that reduces token count.",
    "Performance work must keep correctness evidence. A faster path is not useful unless vector checks still match the host reference and generated text stays readable.",
)


ENDING_REINFORCEMENT_DOCS = (
    "A clean GPT2-BASIC answer is short, factual, and complete. It names the runtime constraint, gives the reason, and ends before repeating the same paragraph.",
    "A good continuation should finish a thought with a period. Short technical sentences are safer for this tiny model than long chains of related topics.",
    "The model should prefer compact explanations. A sentence about cache, timing, memory, or fixed point is strongest when it states one claim and stops cleanly.",
    "Clean endings matter because the evaluator checks whether generated text finishes as a readable sentence. A tiny model should avoid wandering after it has answered the prompt.",
    "Repetition is a quality failure even when the words are spelled correctly. The checkpoint should answer the current prompt, avoid looping, and stop after the useful point.",
    "A useful old-PC model gives one or two concrete sentences. It does not need a long essay to prove that the runtime is real.",
    "The sampler can stop at punctuation after enough output, so the training data should contain many natural sentence endings. This helps the model learn when a response is complete.",
    "Short answers are easier to run, easier to time, and easier to audit. That style fits both the hardware and the small transformer shape.",
)


CAPACITY_REINFORCEMENT_DOCS = (
    "The weight file is the largest artifact in the small checkpoint. Embeddings, transformer blocks, layer normalization values, and the output head all contribute to the fixed byte count.",
    "The output head is expensive because it produces one logit for every vocabulary token. A larger lexicon reduces sequence length, but it also increases the final projection.",
    "A strong vocabulary contains phrases such as fixed-point arithmetic, tokens per second, cache memory, vector parity, context length, output logits, and era-accurate hardware.",
    "A weak vocabulary contains report labels, shell fragments, file names, and broken words. Those pieces make the model sound like its training logs instead of the target domain.",
    "The lexicon builder should prefer complete domain phrases that begin and end on word boundaries. Prefix pieces inside longer words are unsafe because they push the rest of the word back to byte tokens.",
    "A boundary-safe lexicon can still encode prompts that contain unknown words. It falls back to printable byte tokens when no complete piece matches the current position.",
    "The sampler should avoid alphabetic byte runs when a complete lexicon piece is available. That rule reduces malformed words without hiding the vocabulary from prompt encoding.",
    "The training stream should teach the same output contract that the runtime uses. If a token will be discouraged during generation, the model should not learn it as a common target.",
    "A 486SX target makes the fixed-point path important because floating point hardware cannot be assumed. A 486DX2 target can be faster, but the same evidence rules still apply.",
    "Era-accurate does not mean unmeasured. The project needs model reports, vector checks, timing logs, and quality reports before a checkpoint becomes the default.",
    "The DOS executable is part of the model system. Its size, memory manager, tokenizer loader, vector checker, and decode loop all affect whether the checkpoint is practical.",
    "The corpus has to cover the vocabulary that users will ask about. Cache reuse, timing evidence, old-PC limits, fixed-point math, model profiles, and BASIC arrays all need repeated clean phrasing.",
    "A clean paragraph about timing can mention QEMU, hardware, elapsed seconds, generated tokens, and tokens per second. It should also say what the measurement excludes.",
    "A clean paragraph about profiles can compare context length, embedding size, layer count, vocabulary size, memory, speed, and quality. The choice is a tradeoff.",
    "A clean paragraph about cache reuse can mention key vectors, value vectors, attention history, context, memory cost, and fewer repeated operations.",
    "A clean paragraph about fixed point can mention scaled integers, clamps, lookup tables, overflow, precision, logits, and parity against the host reference.",
    "A clean paragraph about the BASIC runtime can mention arrays, loops, model files, tokenizer state, work buffers, and explicit error handling.",
    "A clean paragraph about real inference can mention trained weights, prompt tokens, hidden state, transformer layers, logits, sampler choice, and decoded text.",
    "The best small model is not the one with the most parameters. It is the one that produces useful text while staying inside the memory and speed envelope of the target PC.",
    "The finished project should ship a measured checkpoint, an inspectable DOS runtime, reproducible host tools, clean corpus evidence, and logs showing that the real inference path ran.",
)


DIRECT_COMPLETION_REINFORCEMENT_DOCS = (
    "DOS language models need compact weights, predictable memory, simple model files, honest diagnostics, and a tokenizer shared by host tools and the DOS runtime.",
    "DOS language models need prompt tokens, trained weights, fixed-point math, measured timing, and clear output from the local inference path.",
    "DOS language models need simple file formats and a failure path that stops when required checkpoint data is missing.",
    "DOS language models need enough vocabulary to say technical phrases cleanly while keeping the output head small enough for old hardware.",
    "DOS language models need short context, fixed buffers, repeatable timing, and evidence that the generated text came from model logits.",
    "A BASIC transformer runtime uses plain arrays for weights, tokens, cache vectors, hidden states, logits, and fixed-point work buffers.",
    "A BASIC transformer runtime loads the checkpoint, encodes the prompt, runs attention and feed-forward layers, then decodes the sampled token.",
    "A BASIC transformer runtime keeps memory behavior visible because arrays, loops, and file formats are explicit.",
    "A BASIC transformer runtime is useful when it can be inspected, timed, and checked against host vector references.",
    "A BASIC transformer runtime should produce local generated text from trained weights rather than a canned message.",
    "To improve performance on real hardware, reduce repeated work, keep memory access predictable, use cache data, and measure tokens per second in the decode loop.",
    "To improve performance on real hardware, choose a compact profile, keep buffers fixed, and compare quality against speed and memory.",
    "To improve performance on real hardware, reuse attention history and avoid adding vocabulary pieces that make every output step too expensive.",
    "To improve performance on real hardware, preserve vector parity while replacing slow work with predictable integer operations.",
    "To improve performance on real hardware, tune the model only when evidence shows the change helps the target machine.",
    "GPT2 BASIC on a 486 needs fixed-point arithmetic, predictable memory, a compact checkpoint, short context, and measured local generation.",
    "GPT2 BASIC on a 486 is credible when it loads trained weights, runs transformer layers, and prints text chosen from logits.",
    "GPT2 BASIC on a 486 should be judged by memory use, tokens per second, vector parity, and readable technical completions.",
    "GPT2 BASIC on a 486 is not meant to be a modern assistant. It is a narrow proof that local transformer inference can run on old hardware.",
    "What makes this real inference? The DOS program encodes the prompt, runs transformer layers, computes logits, and samples from trained weights.",
    "What makes this real inference? Changing the prompt changes the model state and the next-token distribution inside the DOS run.",
    "What makes this real inference? The text is produced by the exported checkpoint and fixed-point runtime, not by a table of canned responses.",
    "What makes this real inference? The host trains and exports, but the DOS program performs the forward pass locally.",
    "Explain why a cache matters for text generation. A cache reuses earlier key and value vectors so the next token does not rebuild the full attention history.",
    "Explain why a cache matters for text generation. Cache memory is a deliberate tradeoff because it saves repeated work but consumes predictable RAM.",
    "Explain why a cache matters for text generation. On old hardware, cached attention data can keep the decode loop practical.",
    "How should a DOS model report timing? It should report generated tokens, elapsed seconds, tokens per second, model profile, context length, and measurement source.",
    "How should a DOS model report timing? The timed section belongs around generation, not around boot, loading files, or setup.",
    "How should a DOS model report timing? A useful result says whether the timing came from QEMU or physical hardware.",
    "What limits a tiny transformer on old PCs? Memory, context length, integer arithmetic, cache size, vocabulary size, and output-head cost set the practical limit.",
    "What limits a tiny transformer on old PCs? A larger checkpoint helps only if readable quality improves enough to justify slower generation.",
    "What limits a tiny transformer on old PCs? The whole runtime matters because weights, activations, logits, tokens, and buffers all need memory.",
    "Describe fixed point inference in one sentence. It is transformer inference using scaled integers, clamps, lookup tables, and logits checked against the host reference.",
    "Describe fixed point inference in one sentence. Fixed-point inference lets the DOS runtime run transformer math without requiring floating point hardware.",
    "Describe fixed point inference in one sentence. The model stores scaled weights and computes integer operations close enough to the floating reference.",
    "Why compare model profiles before choosing one? Profiles expose the tradeoff between quality, speed, memory, context length, and vocabulary size.",
    "Why compare model profiles before choosing one? The default should be the smallest checkpoint that passes quality and runtime evidence.",
    "Why compare model profiles before choosing one? A larger model earns its cost only when measurements improve on the target machine.",
    "A clean completion answers the current prompt, finishes the sentence, and stops before introducing a new prompt.",
    "A clean completion should not repeat the question after a complete answer. It should add facts about the same topic or stop.",
    "A clean completion should not jump from cache reuse into fake output paths unless the prompt asks about failure behavior.",
    "A clean completion should not jump from timing into fixed-point internals unless the prompt asks about arithmetic.",
    "A clean completion should not start with an orphaned phrase. It should begin with the subject implied by the prompt.",
    "A clean completion for a fragment prompt must complete the grammar first, then add one concrete technical reason.",
    "A concise answer is better than a long chain for this tiny model. Short technical paragraphs reduce drift and make timing easier to audit.",
    "When a sentence already answers the prompt, the next likely target should be a clean ending rather than a second question.",
    "The corpus should teach complete answers separated by stop points, so the sampler can stop at punctuation without losing the useful content.",
    "Prompt restatement is usually wasted output. The continuation should add information instead of asking the same question again.",
    "Question text is useful for conditioning, but the target continuation should favor the answer, not a second question.",
)


FRAGMENT_COMPLETION_REINFORCEMENT_DOCS = (
    "DOS language models need compact weights, predictable memory, simple model files, honest diagnostics, and a shared tokenizer contract.",
    "DOS language models need prompt tokens, trained weights, fixed-point arithmetic, measured timing, and local generated output.",
    "DOS language models need small checkpoints, short context, fixed buffers, and clear failures when required files are absent.",
    "DOS language models need enough vocabulary to say technical phrases cleanly without making the output head too expensive.",
    "DOS language models need reproducible timing, vector parity, plain file formats, and readable continuations from model logits.",
    "A BASIC transformer runtime uses arrays for weights, tokens, cache vectors, hidden states, logits, and fixed-point work buffers.",
    "A BASIC transformer runtime loads the checkpoint, encodes the prompt, runs attention, applies feed-forward layers, and decodes sampled tokens.",
    "A BASIC transformer runtime keeps memory behavior visible because arrays, loops, and file formats are explicit.",
    "A BASIC transformer runtime is useful when it can be inspected, timed, and compared against host vector references.",
    "A BASIC transformer runtime produces local generated text from trained weights instead of a canned response.",
    "To improve performance on real hardware, reduce repeated work, reuse cache data, keep memory access predictable, and time the decode loop.",
    "To improve performance on real hardware, choose a compact profile and compare quality against speed, memory, and vector parity.",
    "To improve performance on real hardware, preserve fixed-point correctness while replacing slow operations with predictable integer work.",
    "To improve performance on real hardware, use vocabulary pieces that reduce token count without making every logit step too expensive.",
    "To improve performance on real hardware, measure generated tokens per second on the target path before promoting a checkpoint.",
    "GPT2 BASIC on a 486 needs fixed-point arithmetic, predictable memory, a compact checkpoint, short context, and measured local generation.",
    "GPT2 BASIC on a 486 is credible when it loads trained weights, runs transformer layers, and prints text chosen from logits.",
    "GPT2 BASIC on a 486 fits the project when memory use, tokens per second, vector parity, and quality reports all agree.",
    "GPT2 BASIC on a 486 is a narrow proof of local transformer inference on old hardware, not a general modern assistant.",
    "Real inference comes from prompt tokens, trained weights, transformer layers, output logits, and a sampler running in the DOS program.",
    "Real inference is visible when changing the prompt changes the hidden state and the next-token distribution.",
    "Real inference is not a prompt table. The exported checkpoint and fixed-point runtime produce the continuation locally.",
    "Real inference uses the host for training and export, while the DOS machine performs the forward pass.",
    "Cache reuse matters because earlier key and value vectors can be stored instead of rebuilt for every generated token.",
    "Cache reuse trades predictable memory for fewer repeated attention operations in the decode loop.",
    "A cache helps old hardware when it keeps attention history available without exceeding the DOS memory budget.",
    "A timing report names generated tokens, elapsed seconds, tokens per second, model profile, context length, and measurement source.",
    "A timing report measures the generation loop instead of boot time, file loading, or setup work.",
    "A timing report is stronger when it separates QEMU development timing from physical hardware timing.",
    "Old PCs limit the checkpoint through memory, context length, integer arithmetic, cache size, vocabulary size, and output-head cost.",
    "Old PCs reward compact profiles because weights, activations, logits, token history, and buffers all compete for memory.",
    "Old PCs can run useful narrow text generation when the model stays small and the runtime avoids unnecessary repeated work.",
    "Fixed-point inference uses scaled integers, clamps, lookup tables, and logits checked against the host reference.",
    "Fixed-point inference lets the DOS runtime perform transformer math without requiring floating point hardware.",
    "Fixed-point inference is credible only when vector checks show the integer path still matches the trained model closely enough.",
    "Profile comparison exposes the tradeoff between quality, speed, memory, context length, vocabulary size, and parameter count.",
    "The default profile is the smallest checkpoint that passes host quality, DOS vector parity, DOS quality, and runtime evidence.",
    "A larger profile earns its cost only when measurements improve enough to justify slower generation and higher memory use.",
    "Short technical continuations fit this tiny model better than long chains of adjacent topics.",
    "A good continuation completes the current prompt, gives one or two concrete facts, and ends at a readable sentence boundary.",
    "The training corpus uses natural sentence endings so the sampler can stop at punctuation after useful content appears.",
    "Prompt restatement wastes output when the continuation can add technical facts about the requested topic.",
)


def clean_ascii(text: str) -> str:
    text = text.encode("ascii", errors="ignore").decode("ascii")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"\s+", " ", text)
    return "".join(ch for ch in text if 32 <= ord(ch) <= 126).strip()


def topic_answer(topic: Topic, offset: int) -> str:
    fact_a = topic.facts[offset % len(topic.facts)]
    fact_b = topic.detail[offset % len(topic.detail)]
    contrast = topic.contrast[offset % len(topic.contrast)]
    return clean_ascii(f"{fact_a} {fact_b} {contrast}")


def build_gold_docs_v1() -> list[str]:
    docs: list[str] = []

    for topic_idx, topic in enumerate(TOPICS):
        for question_idx, question in enumerate(topic.questions):
            docs.append(clean_ascii(f"{question} {topic_answer(topic, question_idx)}"))

        for idx in range(len(topic.facts)):
            detail = topic.detail[(idx + 1) % len(topic.detail)]
            contrast = topic.contrast[(idx + 2) % len(topic.contrast)]
            docs.append(clean_ascii(f"{topic.facts[idx]} {detail} {contrast}"))

        for idx in range(len(topic.detail)):
            fact = topic.facts[(idx + 1) % len(topic.facts)]
            docs.append(clean_ascii(f"{topic.detail[idx]} {fact}"))

        docs.append(
            clean_ascii(
                f"{topic.key.capitalize()} has an engineering tradeoff. "
                f"{topic.facts[0]} {topic.contrast[0]} {topic.detail[0]}"
            )
        )

        docs.append(
            clean_ascii(
                f"In the DOS model, {topic.facts[1][0].lower() + topic.facts[1][1:]} "
                f"{topic.detail[1]}"
            )
        )

        docs.append(
            clean_ascii(
                f"For GPT2-BASIC, {topic.facts[2][0].lower() + topic.facts[2][1:]} "
                f"{topic.contrast[1]}"
            )
        )

    for first_idx, second_idx in PAIRINGS:
        first = TOPICS[first_idx]
        second = TOPICS[second_idx]
        docs.append(
            clean_ascii(
                f"{first.key.capitalize()} and {second.key} belong together in this system. "
                f"{first.facts[0]} {second.facts[0]}"
            )
        )
        docs.append(
            clean_ascii(
                f"A strong GPT2-BASIC paragraph can connect {first.key} with {second.key}. "
                f"{first.detail[1]} {second.detail[1]}"
            )
        )

    docs.extend(
        clean_ascii(text)
        for text in (
            "GPT2-BASIC is a small transformer demonstration for DOS. It is trained on the host, exported as compact model files, and executed by a fixed-point runtime on era-appropriate hardware.",
            "The demo is useful because every constraint is visible. The model has a short context, a small hidden size, a finite vocabulary, and a runtime that reports what it actually measured.",
            "Clean training text matters because the model is tiny. It cannot average away bad examples the way a large modern model might, so every corrupted phrase can become a likely continuation.",
            "The vocabulary is part of the model's behavior. Clean words and phrases reduce spelling burden, while bad phrases turn into high-probability output pieces.",
            "A good checkpoint produces compact technical prose. It explains the DOS runtime, fixed-point arithmetic, cache reuse, model shape, and timing evidence without wandering into unrelated text.",
            "The small model works best with short factual completions. One or two concrete sentences are more valuable than a long paragraph that repeats itself.",
            "A clean sample names the subject directly, completes the sentence, and stops before it drifts. That style is a better fit for old hardware and a tiny checkpoint.",
            "The target machine makes the result interesting. A 486-compatible PC has to load the weights, run the arithmetic, and print the continuation without remote help.",
            "The host tools and DOS runtime share the tokenizer contract. That keeps training, vector export, quality checks, and runtime generation aligned.",
            "The next useful model needs better text before it needs more size. A cleaner corpus can improve vocabulary contents, target tokens, and visible generation quality at the same time.",
        )
    )

    unique: list[str] = []
    seen: set[str] = set()
    for doc in docs:
        key = doc.lower()
        if key not in seen:
            seen.add(key)
            unique.append(doc)
    return unique


def build_gold_docs_v2_extra() -> list[str]:
    docs: list[str] = list(HELDOUT_REINFORCEMENT_DOCS)
    docs.extend(RUNTIME_REINFORCEMENT_DOCS)
    docs.extend(ENDING_REINFORCEMENT_DOCS)
    docs.extend(CAPACITY_REINFORCEMENT_DOCS)

    for topic in TOPICS:
        for idx, question in enumerate(topic.questions):
            fact = topic.facts[(idx + 1) % len(topic.facts)]
            detail = topic.detail[(idx + 2) % len(topic.detail)]
            contrast = topic.contrast[(idx + 1) % len(topic.contrast)]
            docs.append(clean_ascii(f"{question} {fact} {detail} {contrast}"))

        for idx, fact in enumerate(topic.facts):
            detail = topic.detail[idx % len(topic.detail)]
            contrast = topic.contrast[(idx + 1) % len(topic.contrast)]
            docs.append(
                clean_ascii(
                    f"{fact} {detail} {contrast}"
                )
            )

        for idx, detail in enumerate(topic.detail):
            fact = topic.facts[(idx + 2) % len(topic.facts)]
            docs.append(
                clean_ascii(
                    f"{detail} {fact}"
                )
            )

        docs.append(
            clean_ascii(
                f"{topic.facts[0]} {topic.detail[0]} {topic.contrast[2]}"
            )
        )

    for idx, (first_idx, second_idx) in enumerate(PAIRINGS):
        first = TOPICS[first_idx]
        second = TOPICS[second_idx]
        docs.append(
            clean_ascii(
                f"{first.key.capitalize()} connects naturally with {second.key}. "
                f"{first.facts[idx % len(first.facts)]} {second.detail[idx % len(second.detail)]}"
            )
        )
        docs.append(
            clean_ascii(
                f"{first.contrast[idx % len(first.contrast)]} {second.facts[idx % len(second.facts)]}"
            )
        )

    docs.extend(
        clean_ascii(text)
        for text in (
            "The 4096-token ceiling is already useful on the current DOS contract. More vocabulary would need a memory and hash-table change, so the next gain should come from better pieces and better corpus coverage.",
            "The lexicon should contain complete words and domain phrases. It should not contain report scaffolding, file paths, score labels, or fragments from failed generations.",
            "A better corpus gives the tokenizer better pieces. Good pieces reduce alphabetic byte fallback, which lowers the chance of malformed words during generation.",
            "The corpus should teach the model to answer cache prompts with cache words, timing prompts with measurement words, and profile prompts with quality and speed tradeoffs.",
            "Coverage matters because a tiny model cannot infer every phrasing from a handful of examples. Several clean paraphrases are better than one long mined report.",
            "The model can be useful as a compact technical explainer for the project. It can answer why the DOS runtime is real, how timing is measured, and what constrains old hardware.",
            "A narrow model is acceptable when the target is narrow. GPT2-BASIC does not need general world knowledge to demonstrate local transformer inference on an era-accurate PC.",
            "The final checkpoint should be chosen by evidence. Host quality, DOS vector parity, DOS quality, runtime memory, and timing all have to agree before promotion.",
            "If a candidate improves text but breaks vector parity, it is not ready. If it passes vectors but repeats paragraphs, it is still not ready.",
            "The model size is only one part of the project. Tokenizer contents, corpus cleanliness, runtime correctness, and measured speed determine whether the result is useful.",
        )
    )
    return docs


def build_gold_docs(version: str = DEFAULT_VERSION) -> list[str]:
    if version not in DEFAULT_OUTPUTS:
        raise ValueError(f"unknown gold curriculum version: {version}")
    docs = build_gold_docs_v1()
    if version in {"v2", "v3", "v4"}:
        docs.extend(build_gold_docs_v2_extra())
    if version == "v3":
        docs.extend(clean_ascii(text) for text in DIRECT_COMPLETION_REINFORCEMENT_DOCS)
    if version == "v4":
        docs.extend(clean_ascii(text) for text in FRAGMENT_COMPLETION_REINFORCEMENT_DOCS)

    unique: list[str] = []
    seen: set[str] = set()
    for doc in docs:
        key = doc.lower()
        if key not in seen:
            seen.add(key)
            unique.append(doc)
    return unique


def audit_doc(doc: str) -> list[str]:
    issues: list[str] = []
    if len(doc) < 80:
        issues.append("too_short")
    if len(doc) > 560:
        issues.append("too_long")
    for pattern in BANNED_PATTERNS:
        if re.search(pattern, doc, flags=re.IGNORECASE):
            issues.append("banned_pattern")
            break
    for pattern in CORRUPT_PATTERNS:
        if re.search(pattern, doc, flags=re.IGNORECASE):
            issues.append("corrupt_pattern")
            break
    alpha = sum(1 for ch in doc if ch.isalpha())
    if alpha / max(1, len(doc)) < 0.55:
        issues.append("low_alpha")
    if re.search(r"\s{2,}", doc):
        issues.append("extra_space")
    return issues


def token_distribution(docs: list[str]) -> tuple[dict[str, int], float, int, list[str]]:
    tokenizer = build_lexicon_tokenizer(docs, 4096, min_count=1, max_phrase_words=3)
    counts = {"lexicon": 0, "alpha_byte": 0, "byte": 0, "other": 0}
    for doc in docs:
        for token in tokenizer.encode(doc, output_safe=True):
            if BYTE_OFFSET <= token < BYTE_VOCAB_SIZE:
                byte = token - BYTE_OFFSET
                if chr(byte).isalpha():
                    counts["alpha_byte"] += 1
                else:
                    counts["byte"] += 1
            elif token >= BYTE_VOCAB_SIZE:
                counts["lexicon"] += 1
            else:
                counts["other"] += 1
    total = max(1, sum(counts.values()))
    alpha_byte_ratio = counts["alpha_byte"] / total
    top_pieces = [
        tokenizer.id_to_piece[token_id].decode("ascii", errors="ignore")
        for token_id in range(BYTE_VOCAB_SIZE, min(tokenizer.vocab_size, BYTE_VOCAB_SIZE + 80))
    ]
    return counts, alpha_byte_ratio, tokenizer.vocab_size, top_pieces


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def report_text(
    version: str,
    output: Path,
    docs: list[str],
    counts: dict[str, int],
    alpha_ratio: float,
    vocab_size: int,
    top_pieces: list[str],
) -> str:
    bad_docs = [(idx + 1, audit_doc(doc), doc) for idx, doc in enumerate(docs) if audit_doc(doc)]
    lines = [
        f"# GPT2-BASIC Gold Curriculum {version}",
        "",
        "This is a hand-curated narrow corpus for the large lexicon tokenizer path.",
        "It avoids report mining, scoring instructions, code paths, and previous malformed generations.",
        "",
        "## Summary",
        "",
        f"- Corpus: `{display_path(output)}`",
        f"- Documents: {len(docs)}",
        f"- Characters: {sum(len(doc) for doc in docs)}",
        f"- Audit failures: {len(bad_docs)}",
        f"- Probe lexicon vocab size: {vocab_size}",
        f"- Probe lexicon targets: {counts['lexicon']}",
        f"- Probe alphabetic byte targets: {counts['alpha_byte']}",
        f"- Probe alphabetic byte share: {alpha_ratio:.3f}",
        "",
        "## Top Probe Vocabulary Pieces",
        "",
    ]
    for piece in top_pieces:
        lines.append(f"- `{piece}`")
    if bad_docs:
        lines.extend(["", "## Audit Failures", ""])
        for idx, issues, doc in bad_docs[:20]:
            lines.append(f"- Document {idx}: {', '.join(issues)}: {doc[:160]}")
    return "\n".join(lines) + "\n"


def write_outputs(version: str, output: Path, report: Path) -> tuple[list[str], dict[str, int], float, int]:
    docs = build_gold_docs(version)
    failures = [(idx + 1, audit_doc(doc), doc) for idx, doc in enumerate(docs) if audit_doc(doc)]
    if failures:
        preview = "; ".join(f"{idx}:{','.join(issues)}" for idx, issues, _doc in failures[:10])
        raise ValueError(f"gold corpus audit failed: {preview}")
    counts, alpha_ratio, vocab_size, top_pieces = token_distribution(docs)
    if alpha_ratio > 0.10:
        raise ValueError(f"alphabetic byte target share too high: {alpha_ratio:.3f}")
    output.parent.mkdir(parents=True, exist_ok=True)
    report.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n\n".join(docs) + "\n", encoding="ascii")
    report.write_text(report_text(version, output, docs, counts, alpha_ratio, vocab_size, top_pieces), encoding="ascii")
    return docs, counts, alpha_ratio, vocab_size


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", choices=tuple(DEFAULT_OUTPUTS), default=DEFAULT_VERSION)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--report", type=Path)
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    output = args.output or DEFAULT_OUTPUTS[args.version]
    report = args.report or DEFAULT_REPORTS[args.version]

    if args.self_test:
        docs = build_gold_docs(args.version)
        if args.version == "v1":
            assert 150 <= len(docs) <= 250
        elif args.version == "v2":
            assert 250 <= len(docs) <= 430
            assert 60000 <= sum(len(doc) for doc in docs) <= 90000
        elif args.version == "v3":
            assert 360 <= len(docs) <= 520
            assert 85000 <= sum(len(doc) for doc in docs) <= 115000
        else:
            assert 360 <= len(docs) <= 510
            assert 85000 <= sum(len(doc) for doc in docs) <= 110000
        assert not any(audit_doc(doc) for doc in docs)
        counts, alpha_ratio, vocab_size, top_pieces = token_distribution(docs)
        assert alpha_ratio <= 0.10
        assert vocab_size > BYTE_VOCAB_SIZE
        assert top_pieces
        print("trace_scope gold_curriculum_contract")
        print("trace build_gold_docs")
        print("trace build_gold_docs_v1")
        print("trace build_gold_docs_v2_extra")
        print("trace DIRECT_COMPLETION_REINFORCEMENT_DOCS")
        print("trace FRAGMENT_COMPLETION_REINFORCEMENT_DOCS")
        print("trace topic_answer")
        print("trace display_path")
        print("trace write_outputs")
        print("trace audit_doc")
        print("trace token_distribution")
        print("trace report_text")
        print(f"PROBE_OK gold_version={args.version}")
        print(f"PROBE_OK gold_docs={len(docs)}")
        print(f"PROBE_OK gold_chars={sum(len(doc) for doc in docs)}")
        print(f"PROBE_OK gold_vocab_probe={vocab_size}")
        print(f"PROBE_OK alpha_byte_share={alpha_ratio:.3f}")
        print("PROBE_OK main cli_entry=available")
        return

    docs, counts, alpha_ratio, vocab_size = write_outputs(args.version, output, report)
    print(
        f"wrote {output} docs={len(docs)} chars={sum(len(doc) for doc in docs)} "
        f"vocab_probe={vocab_size} alpha_byte_share={alpha_ratio:.3f}"
    )
    print(f"wrote {report}")


if __name__ == "__main__":
    main()
