#!/usr/bin/env python3
"""Build compact assistant pack retrieval databases.

KDB.TXT is the runtime recall surface. HELP.TXT and KNOW.TXT stay readable
authoring files; this script compiles their rows into shorter keyword-indexed
records so the DOS shell scans less text before answering. KDBIDX.TXT and
KDB?.TXT bucket files are generated sidecars for faster DOS recall.
"""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

from assistant_pack_contract import HelpRow, PackContract, load_all_pack_contracts


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PACK_ROOT = ROOT / "assets" / "gpt2_basic" / "PACKS"

STOPWORDS = {
    "the",
    "and",
    "for",
    "with",
    "what",
    "when",
    "where",
    "why",
    "how",
    "can",
    "you",
    "your",
    "this",
    "that",
    "from",
    "about",
    "into",
    "should",
    "would",
    "could",
    "then",
    "than",
    "they",
    "them",
    "that",
    "there",
    "here",
    "will",
    "each",
    "use",
    "uses",
}

BUCKET_CHARS = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"
BUCKET_NAME_RE = re.compile(r"^KDB[0-9A-Z]\.TXT$")


@dataclass(frozen=True)
class KdbRow:
    terms: str
    title: str
    body: str


def words(text: str) -> list[str]:
    return re.findall(r"[a-z0-9][a-z0-9.:-]*", text.lower())


def compact_terms(row: HelpRow, limit: int = 18) -> str:
    selected: list[str] = []
    seen: set[str] = set()
    for source in (row.key, row.title, row.text):
        for word in words(source):
            cleaned = word.strip(".:-")
            if len(cleaned) < 3 or cleaned in STOPWORDS:
                continue
            if cleaned not in seen:
                selected.append(cleaned)
                seen.add(cleaned)
            if len(selected) >= limit:
                return " ".join(selected)
    return " ".join(selected)


def kdb_rows(pack: PackContract) -> list[KdbRow]:
    rows: list[KdbRow] = []
    seen: set[tuple[str, str]] = set()
    for row in (*pack.help_rows, *pack.knowledge_rows):
        identity = (row.title, row.text)
        if identity in seen:
            continue
        seen.add(identity)
        terms = compact_terms(row)
        if not terms:
            terms = row.key
        rows.append(KdbRow(terms, row.title, row.text))
    return rows


def bucket_name(bucket: str) -> str:
    return f"KDB{bucket.upper()}.TXT"


def row_buckets(row: KdbRow, limit: int = 4) -> tuple[str, ...]:
    buckets: list[str] = []
    seen: set[str] = set()
    for word in words(row.terms):
        if not word:
            continue
        bucket = word[0].upper()
        if bucket in BUCKET_CHARS and bucket not in seen:
            seen.add(bucket)
            buckets.append(bucket)
            if len(buckets) >= limit:
                break
    return tuple(buckets)


def bucketed_rows(pack: PackContract) -> dict[str, list[KdbRow]]:
    buckets: dict[str, list[KdbRow]] = {bucket: [] for bucket in BUCKET_CHARS}
    for row in kdb_rows(pack):
        for bucket in row_buckets(row):
            buckets[bucket].append(row)
    return {bucket: rows for bucket, rows in buckets.items() if rows}


def render_kdb(pack: PackContract) -> str:
    lines = [
        "# terms|title|body",
        "# Generated by scripts/build_assistant_kdb.py from HELP.TXT and KNOW.TXT.",
    ]
    for row in kdb_rows(pack):
        lines.append(f"{row.terms}|{row.title}|{row.body}")
    return "\n".join(lines) + "\n"


def render_bucket(bucket: str, rows: list[KdbRow]) -> str:
    lines = [
        "# terms|title|body",
        f"# Generated KDB bucket {bucket}. Rebuild with scripts/build_assistant_kdb.py --write.",
    ]
    for row in rows:
        lines.append(f"{row.terms}|{row.title}|{row.body}")
    return "\n".join(lines) + "\n"


def render_index(pack: PackContract) -> str:
    buckets = bucketed_rows(pack)
    lines = [
        "# bucket|entries|file",
        "# Generated by scripts/build_assistant_kdb.py from KDB.TXT.",
    ]
    for bucket in BUCKET_CHARS:
        rows = buckets.get(bucket, [])
        if rows:
            lines.append(f"{bucket}|{len(rows)}|{bucket_name(bucket)}")
    return "\n".join(lines) + "\n"


def render_bucket_files(pack: PackContract) -> dict[str, str]:
    return {
        bucket_name(bucket): render_bucket(bucket, rows)
        for bucket, rows in bucketed_rows(pack).items()
    }


def stale_bucket_files(pack: PackContract, expected_names: set[str]) -> list[Path]:
    stale: list[Path] = []
    for path in pack.kdb_path.parent.iterdir():
        if BUCKET_NAME_RE.fullmatch(path.name.upper()) and path.name.upper() not in expected_names:
            stale.append(path)
    return stale


def write_or_check(pack_root: Path, write: bool) -> int:
    failures: list[str] = []
    for pack in load_all_pack_contracts(pack_root):
        expected = render_kdb(pack)
        target = pack.kdb_path
        expected_index = render_index(pack)
        index_target = pack.kdb_index_path
        bucket_files = render_bucket_files(pack)
        expected_bucket_names = {name.upper() for name in bucket_files}
        if write:
            target.write_text(expected, encoding="ascii")
            index_target.write_text(expected_index, encoding="ascii")
            for name, text in bucket_files.items():
                (target.parent / name).write_text(text, encoding="ascii")
            for stale in stale_bucket_files(pack, expected_bucket_names):
                stale.unlink()
            bucket_entries = sum(text.count("\n") - 2 for text in bucket_files.values())
            print(
                "WROTE_ASSISTANT_KDB|"
                f"pack={pack.pack_id}|path={target}|rows={len(kdb_rows(pack))}|"
                f"buckets={len(bucket_files)}|bucket_entries={bucket_entries}"
            )
            continue
        current = target.read_text(encoding="ascii") if target.exists() else ""
        current_index = index_target.read_text(encoding="ascii") if index_target.exists() else ""
        stale_files = stale_bucket_files(pack, expected_bucket_names)
        bucket_mismatches = [
            name
            for name, text in bucket_files.items()
            if not (target.parent / name).exists() or (target.parent / name).read_text(encoding="ascii") != text
        ]
        if current != expected or current_index != expected_index or bucket_mismatches or stale_files:
            failures.append(pack.pack_id)
            print(f"ASSISTANT_KDB_STALE|pack={pack.pack_id}|path={target}")
        else:
            print(f"ASSISTANT_KDB_OK|pack={pack.pack_id}|rows={len(kdb_rows(pack))}|buckets={len(bucket_files)}")
    if failures:
        print("ASSISTANT_KDB_CHECK_FAILED|packs=" + ",".join(failures))
        return 1
    print("PROBE_OK assistant_kdb=1")
    return 0


def self_test() -> None:
    row = HelpRow("fat image full", "FAT image full", "Remove host-only training files or grow the disk image.")
    terms = compact_terms(row)
    assert "fat" in terms
    assert "image" in terms
    assert "training" in terms
    pack = load_all_pack_contracts(DEFAULT_PACK_ROOT)[0]
    rendered = render_kdb(pack)
    assert rendered.startswith("# terms|title|body\n")
    assert "Better prompts" in rendered
    index = render_index(pack)
    assert index.startswith("# bucket|entries|file\n")
    assert "B|" in index
    bucket_files = render_bucket_files(pack)
    assert "KDBB.TXT" in bucket_files
    assert "Better prompts" in bucket_files["KDBB.TXT"]
    print("PROBE_OK assistant_kdb_self_test=1")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pack-root", type=Path, default=DEFAULT_PACK_ROOT)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return
    raise SystemExit(write_or_check(args.pack_root, write=args.write or not args.check))


if __name__ == "__main__":
    main()
